apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  namespace: dev
  name: developer-role 

rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-to-dev-user
  namespace: dev
subjects:
- kind: User
  name: dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: developer-role 
  apiGroup: rbac.authorization.k8s.io
