frontend:
  repository: lbabay.azurecr.io
  tag: "v1.2"
  image: simple-frontend
  replicaCount: 1
  

backend:
  repository: lbabay.azurecr.io
  tag: "v1.2"
  image: simple-backend
  replicaCount: 1
 

storage:
  storageAmount: 500Mi
  reclaimPolicy: Retain 
  storagePath: /mongo-data

db: 
  serviceName: db-headless
  storageAmount: 500Mi

services: 
  frontend:
    serviceType: NodePort
    ports:
      port: 80
      targetPort: 80
  backend:
    serviceType: ClusterIP
    ports:
      port: 3032
      targetPort: 3032
    
  