apiVersion: v1
kind: Pod 
metadata:
  name: local-logs

spec:
  containers:
    - name: log-sender
      image: nginx
      volumeMounts:
      - mountPath: /var/www/html/
        name: log-volume
    
    - name: log-reader
      image: ubuntu
      command: ["bash", "-c", "tail -f > /dev/null"]
      volumeMounts:
      - mountPath: /tmp/
        name: log-volume

  volumes: 
  - name: log-volume
    hostPath:
      path: /data/pv0001
      type: DirectoryOrCreate