apiVersion: batch/v1
kind: cronJob
metadata:
  name: cron-echo

spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      completions: 2
      template:
        spec:
          containers:
            - name: cron-echo
              image: ubuntu
              command: ["echo", "ran"]
          restartPolicy: Never
    
    
