apiVersion: batch/v1
kind: CronJob
metadata:
  name: lab3a

spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      parallelism: 2 
      backoffLimit: 4
      template:
        spec:
          containers:
            - name: busybox
              image: busybox
              command: ["/bin/sh", "-c", "echo 'hello from k8s cronjob'"]
          restartPolicy: OnFailure