apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-app
  labels:
    app: nginx
    env: dev


spec: 
  template:
    metadata: #this is everything from the pod-def after apiVersion and kind
      name: nginx 
      labels:
        app: nginx
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3