apiVersion: v1
kind: Pod 
metadata:
  name: multi-pod
spec:
  containers:
    - name: data-pod 
      image: ubuntu
      command: ["bash", "-c", "echo 'test' > /pod-data/index.html; tail -f > /dev/null"]
      volumeMounts:
        - mountPath: /pod-data
          name: shared-data

    - name: exposed-pod
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: shared-data

  volumes:
  - name: shared-data
    emptyDir: {}
    
    