FROM node AS build 

WORKDIR /usr/src/app 
COPY package.json package-lock.json /usr/src/app/
RUN npm install 
COPY . /usr/src/app/
RUN npm run build 

FROM nginx 

WORKDIR /var/www/html
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /var/www/html/



