apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          

