apiVersion: v1
kind: PersistentVolume 
metadata:
  name: mini-pv

spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: mini-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi 
---
apiVersion: v1
kind: Pod 
metadata:
  name: ubuntu

spec: 
  containers:
  - name: ubuntu
    command: ["tail", "-f", ">", "/dev/null"]
    image: ubuntu 
    volumeMounts: 
    - mountPath: /opt
      name: pvc

  volumes: 
    - name: pvc 
      persistentVolumeClaim: 
        claimName: mini-pvc
---  
apiVersion: v1
kind: Pod 
metadata:
  name: ubuntu2

spec: 
  containers:
  - name: ubuntu2
    command: ["tail", "-f", ">", "/dev/null"]
    image: ubuntu 
    volumeMounts: 
    - mountPath: /var
      name: pvc

  volumes: 
    - name: pvc 
      persistentVolumeClaim: 
        claimName: mini-pvc

  