apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: alpha-deploy
  annotations:
    kubernetes.io/change-cause: "rollout of v1.1"
spec: 
  replicas: 2
  strategy: 
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  selector: 
    matchLabels: 
      app: alpha
  template:
    metadata:
      labels:
        app: alpha
    spec:
      containers: 
        - name: alpha
          image: lbabay.azurecr.io/alpha:v1.0
---
apiVersion: v1 
kind: Service 
metadata:
  name: alpha
spec:
  type: NodePort 
  selector:
    app: alpha
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007