apiVersion: apps/v1
kind: Deployment 
metadata:
  name: alpha
  labels: 
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: alpha
          image: lbabay.azurecr.io/alpha:v1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-svc
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30005