#2 deployments, 2 services, 1 ingress 
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: alpha
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: alpha 
  template:
    metadata:
      labels:
        app: alpha 
    spec:
      containers:
        - name: alpha 
          image: lbabay.azurecr.io/alpha:v1.0 
          ports:
           - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: bravo
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: bravo
  template:
    metadata:
      labels:
        app: bravo
    spec:
      containers:
        - name: bravo
          image: lbabay.azurecr.io/bravo:v1.0 
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service 
metadata:
  name: alpha-service
spec:
  type: NodePort
  selector:
    app: alpha 
  ports:
    - port: 3000
      targetPort: 3000 
--- 
apiVersion: v1
kind: Service 
metadata:
  name: bravo-service
spec:
  type: NodePort
  selector:
    app: bravo 
  ports:
    - port: 3000
      targetPort: 3000 
---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: alpha-bravo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec: 
  rules:
    - host: alpha-bravo.info
      http:
        paths:
          - path: /alpha
            pathType: Prefix
            backend:
              service:
                name: bravo-service
                port:
                  number: 3000
          - path: /bravo
            pathType: Prefix
            backend:
              service:
                name: alpha-service
                port:
                  number: 3000


