apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    tier: db 
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      labels:
        tier: db 
    spec:
      containers:
        - name: mongodb
          image: mongo 
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service 
metadata:
  name: mongo-ip
spec:
  type: ClusterIP
  selector:
    tier: db
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels: 
        tier: app
    spec:
      containers:
        - name: backend-app 
          image: lbabay.azurecr.io/backend:v1.0
          env:
            - name: DB
              value: 