apiVersion: v1 
kind: Pod 
metadata:
  name: blue 

spec: 
  containers:
    - name: blue 
      image: nginx 
  
  tolerations: 
    - key: "color"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"