apiVersion: v1
kind: Pod 
metadata:
  name: nginx1
  labels: 
    app: nginx
spec:
  containers: 
    - name: nginx1
      image: nginx
---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx2
  labels: 
    app: nginx2
spec:
  containers: 
    - name: nginx2
      image: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress-nginx
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
    - Ingress 
