apiVersion: v1 
kind: Pod 
metadata:
  name: lab1
spec:
  containers:
    - name: html-host
      image: nginx 
      volumeMounts: 
        - name: html-volume 
          mountPath: /usr/share/nginx/html/
    - name: html-source 
      image: nginx
      command: 
        - "/bin/sh"
        - "-c"
        - "echo 'hello from the source container' > /tmp/index.html"
      volumeMounts:
        - name: html-volume
          mountPath: /tmp/
  volumes:
    - name: html-volume
      emptyDir: {}