apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: myuser-dev
  namespace: development
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
  name: myuser-dev-binding
  namespace: development 
subjects:
- kind: User 
  name: myuser
  apiGroup: rbac.authorization.k8s.io
roleRef: 
    kind: Role 
    name: myuser-dev
    apiGroup: rbac.authorization.k8s.io