apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-to-role
  namespace: default
subjects:
  - namespace: default
    kind: ServiceAccount
    name: pod-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader-role
---
# secrets are no longer manually generated for service accounts 
apiVersion: v1 
kind: Secret 
metadata:
  name: pod-reader-secret
  annotations:
    kubernetes.io/service-account.name: pod-reader
type: kubernetes.io/service-account-token
