apiVersion: v1 
kind: Pod 
metadata:
  name: ubuntu

spec:
  containers:
    - name: ubuntu
      image: ubuntu 
      command: ["tail", "-f", "<", "/dev/null"]
  serviceAccountName: testing-sa
      