# storage for mongodb
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-storage
spec: 
  storageClassName: "local"
  capacity:
    storage: {{ .Values.storage.storageAmount }}
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.storage.reclaimPolicy }} 
  hostPath:
    path: {{ .Values.storage.storagePath }}
    type: Directory
    
    