apiVersion: v1 
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-svc
spec:
  type: NodePort
  selector: 
    tier: frontend
  ports:
    - port: {{ .Values.services.frontend.ports.port }}
      targetPort: {{ .Values.services.frontend.ports.targetPort }} 
      nodePort: 30010
---
apiVersion: v1 
kind: Service 
metadata:
  name: api
  labels:
    tier: api 
spec: 
  type: {{ .Values.services.backend.serviceType }}
  selector:
    tier: api 
  ports: 
    - port: {{ .Values.services.backend.ports.port}}
      targetPort:  {{ .Values.services.backend.ports.targetPort}}