apiVersion: v1
kind: Pod 
metadata:
  name: proxy-pod
  labels:
    app: proxy-app

spec:
  containers:
    - name: react-app
      image: ckad-demo-app:latest
      imagePullPolicy: Never
    - name: nginx-proxy
      image: nginx 
      volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/
      ports:
        - containerPort: 80
  volumes:
    - name: nginx-proxy-config
      configMap:
        name: nginx-proxy-config
---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: nginx-proxy-config

data:
  nginx.conf: |
    events { 
    worker_connections 1024;
      }
      http{ 
      server { 
        listen 80;
        server_name ckaddev.com;

        location / { 
          proxy_pass "http://localhost:3000";
      }


      }
      }
--- 
apiVersion: v1
kind: Service 
metadata: 
  name: proxy-service 
spec:
  selector:
    app: proxy-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80



