apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: alpha-deploy
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: alpha
  template:
    metadata:
      labels:
        app: alpha
    spec:
      containers: 
        - name: alpha
          image: lbabay.azurecr.io/alpha:v1.0