apiVersion: apps/v1
kind: Deployment 
metadata:
  name: webapp-deployment # name of the pods + name of the deployment
  labels:
    app: react 
    tier: frontend
    env: dev 

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 7 
      maxUnavailable: 2  
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: react-deployment
      labels:
        app: react 
        tier: frontend
        env: dev 
    spec:
      containers:
        - name: react-container # name of the containers inside the pods 
          image: nginx