apiVersion: apps/v1
kind: Deployment 
metadata:
  name: app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      securityContext:
        runAsUser: 2000
      containers:
        - name: ubuntu
          image: ubuntu
          command: 
            - "bin/bash"
            - "-c"
            - "tail -f > /dev/null"
