apiVersion: v1
kind: ConfigMap
metadata:
  name: lab1a

data:
  index.html: | 
    "Hello from config map"
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: lab1a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab1a
  template:
    metadata:
      labels: 
        app: lab1a
    spec:
      containers:
        - name: lab1a-nginx
          image: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: index-volume
      volumes: 
        - name: index-volume
          configMap:
            name: lab1a
            items:
              - key: "index.html"
                path: "index.html"
---
apiVersion: v1 
kind: Service 
metadata:
  name: lab1a-svc
spec:
  type: NodePort
  selector:
    app: lab1a 
  ports: 
    - port: 80
      targetPort: 80
    